version: "3.4"
services:
  nginx:
    image: gripo/gripo-nginx:1.0
    environment:
      - LISTEN_PORT=80
      - API_BACKEND=http://gripo-application:5080
      - TERMINAL_BACKEND=http://gripo-terminal:8377
      - FRONTEND_BACKEND=http://gripo-frontend:3000
    depends_on:
      - gripo-application
      - gripo-frontend
    ports:
      - 80:80
    networks:
      - gripo
  gripo-db:
    image: gripo/gripo-db:1.0
    volumes:
      - gripodb_data_volume:/data/db
    networks:
      - gripo
  gripo-redis:
    image: gripo/gripo-redis:1.0
    container_name: gripo-redis
    networks:
      - gripo
  gripo-application:
    container_name: gripo-application
    image: gripo/gripo-application:beta-1.0
    environment:
      - GRIPO_SERVER_ADDRESS=:5080
    depends_on:
      - gripo-db
    networks:
      - gripo
  gripo-frontend:
    container_name: gripo-frontend
    image: gripo/gripo-frontend:beta-1.0
    restart: always
    networks:
      - gripo
  gripo-terminal:
    container_name: gripo-terminal
    image: gripo/gripo-terminal:beta-1.0
    restart: always
    networks:
      - gripo
volumes:
  gripodb_data_volume:
networks:
  gripo:
    driver: bridge